/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

struct _IO_FILE ;
struct _IO_codecvt ;
struct _IO_marker ;
struct _IO_wide_data ;
struct timeval ;
extern int gettimeofday(struct timeval *tv , void *tz ) ;
extern int pthread_cond_broadcast(int *cond ) ;
char **_global_argv  =    (char **)0;
extern int getpagesize() ;
extern int posix_memalign(void **memptr , unsigned int alignment , unsigned int size ) ;
extern int pthread_join(void *thread , void **value_ptr ) ;
extern int open(char const   *filename , int oflag  , ...) ;
extern unsigned int strlen(char const   *s ) ;
extern int pthread_barrier_destroy(int *barrier ) ;
extern int pthread_mutex_init(int *mutex , int *attr ) ;
extern int strncmp(char const   *s1 , char const   *s2 , unsigned int maxlen ) ;
extern int printf(char const   *format  , ...) ;
unsigned long _1_main_flag_func_1(int left , int right , unsigned long thenExpr ,
                                  unsigned long elseExpr ) ;
int _global_argc  =    0;
extern int pthread_cond_signal(int *cond ) ;
extern int scanf(char const   *format  , ...) ;
extern int pthread_barrier_init(int *barrier , int *attr , unsigned int count ) ;
extern int raise(int sig ) ;
char **_global_envp  =    (char **)0;
extern int unlink(char const   *filename ) ;
unsigned long _1_main_flag_func_3(int left , int right , unsigned long thenExpr ,
                                  unsigned long elseExpr ) ;
extern int pthread_barrier_wait(int *barrier ) ;
extern double difftime(long tv1 , long tv0 ) ;
extern int puts(char const   *__s ) ;
typedef struct _IO_FILE FILE;
extern char *fgets(char * __restrict  __s , int __n , FILE * __restrict  __stream )  __attribute__((__access__(__write_only__,1,2))) ;
extern void *memcpy(void *s1 , void const   *s2 , unsigned int size ) ;
extern int pthread_mutex_lock(int *mutex ) ;
extern void *dlsym(void *handle , char *symbol ) ;
extern int gethostname(char *name , unsigned int namelen ) ;
extern unsigned long strtoul(char const   *str , char const   *endptr , int base ) ;
extern void abort() ;
extern void free(void *ptr ) ;
extern int fprintf(struct _IO_FILE *stream , char const   *format  , ...) ;
extern void signal(int sig , void *func ) ;
int main(int _formal_argc , char **_formal_argv , char **_formal_envp ) ;
extern void exit(int status ) ;
unsigned long _1_main_flag_func_2(int left , int right , unsigned long thenExpr ,
                                  unsigned long elseExpr ) ;
typedef long __off64_t;
extern int mprotect(void *addr , unsigned int len , int prot ) ;
extern int close(int filedes ) ;
extern double strtod(char const   *str , char const   *endptr ) ;
extern double log(double x ) ;
extern FILE *stdin ;
extern double ceil(double x ) ;
typedef unsigned long size_t;
extern int fclose(void *stream ) ;
extern int fcntl(int filedes , int cmd  , ...) ;
extern int pthread_cond_wait(int *cond , int *mutex ) ;
extern void perror(char const   *str ) ;
extern int write(int filedes , void *buf , unsigned int nbyte ) ;
extern int pthread_cond_init(int *cond , int *attr ) ;
extern int ptrace(int request , void *pid , void *addr , int data ) ;
extern float strtof(char const   *str , char const   *endptr ) ;
extern unsigned int strnlen(char const   *s , unsigned int maxlen ) ;
struct timeval {
   long tv_sec ;
   long tv_usec ;
};
extern void qsort(void *base , unsigned int nel , unsigned int width , int (*compar)(void *a ,
                                                                                     void *b ) ) ;
extern long clock(void) ;
extern long time(long *tloc ) ;
extern int rand() ;
extern int read(int filedes , void *buf , unsigned int nbyte ) ;
typedef void _IO_lock_t;
extern int strcmp(char const   *a , char const   *b ) ;
extern void *fopen(char const   *filename , char const   *mode ) ;
extern double sqrt(double x ) ;
typedef long __off_t;
struct _IO_FILE {
   int _flags ;
   char *_IO_read_ptr ;
   char *_IO_read_end ;
   char *_IO_read_base ;
   char *_IO_write_base ;
   char *_IO_write_ptr ;
   char *_IO_write_end ;
   char *_IO_buf_base ;
   char *_IO_buf_end ;
   char *_IO_save_base ;
   char *_IO_backup_base ;
   char *_IO_save_end ;
   struct _IO_marker *_markers ;
   struct _IO_FILE *_chain ;
   int _fileno ;
   int _flags2 ;
   __off_t _old_offset ;
   unsigned short _cur_column ;
   signed char _vtable_offset ;
   char _shortbuf[1] ;
   _IO_lock_t *_lock ;
   __off64_t _offset ;
   struct _IO_codecvt *_codecvt ;
   struct _IO_wide_data *_wide_data ;
   struct _IO_FILE *_freeres_list ;
   void *_freeres_buf ;
   size_t __pad5 ;
   int _mode ;
   char _unused2[(15U * sizeof(int ) - 4U * sizeof(void *)) - sizeof(size_t )] ;
};
extern void *malloc(unsigned int size ) ;
extern int snprintf(char *str , unsigned int size , char const   *format  , ...) ;
extern long strtol(char const   *str , char const   *endptr , int base ) ;
extern int nanosleep(int *rqtp , int *rmtp ) ;
extern int pthread_mutex_unlock(int *mutex ) ;
extern int pthread_create(void *thread , void *attr , void *start_routine , void *arg ) ;
extern int atoi(char const   *s ) ;
unsigned long _1_main_flag_func_0(int left , int right , unsigned long thenExpr ,
                                  unsigned long elseExpr ) ;
extern int fscanf(struct _IO_FILE *stream , char const   *format  , ...) ;
extern int fseek(struct _IO_FILE *stream , long offs , int whence ) ;
void megaInit(void) ;
unsigned long _1_main_flag_func_1(int left , int right , unsigned long thenExpr ,
                                  unsigned long elseExpr ) 
{ 
  register unsigned long tmp5 ;
  unsigned long r6 ;
  unsigned long notr7 ;

  {
  __asm__  volatile   ("cmpl %[right], %[left]\n;\t"
                       "pushf\n;\t"
                       "popq %[tmp5]\n;\t": [tmp5] "=r" (tmp5): [left] "r" (left),
                       [right] "r" (right));
  r6 = ((tmp5 >> 6) & 1) & 1;
  notr7 = ~ r6 & 1;
  return (r6 * thenExpr + notr7 * elseExpr);
}
}
unsigned long _1_main_flag_func_0(int left , int right , unsigned long thenExpr ,
                                  unsigned long elseExpr ) 
{ 
  register unsigned long tmp5 ;
  unsigned long r6 ;
  unsigned long notr7 ;

  {
  __asm__  volatile   ("cmpl %[right], %[left]\n;\t"
                       "pushf\n;\t"
                       "popq %[tmp5]\n;\t": [tmp5] "=r" (tmp5): [left] "r" (left),
                       [right] "r" (right));
  r6 = ((tmp5 >> 6) & 1) & 1;
  notr7 = ~ r6 & 1;
  return (r6 * thenExpr + notr7 * elseExpr);
}
}
unsigned long _1_main_flag_func_3(int left , int right , unsigned long thenExpr ,
                                  unsigned long elseExpr ) 
{ 
  register unsigned long tmp5 ;
  unsigned long r6 ;
  unsigned long notr7 ;

  {
  __asm__  volatile   ("cmpl %[right], %[left]\n;\t"
                       "pushf\n;\t"
                       "popq %[tmp5]\n;\t": [tmp5] "=r" (tmp5): [left] "r" (left),
                       [right] "r" (right));
  r6 = ((tmp5 >> 6) & 1) & 1;
  notr7 = ~ r6 & 1;
  return (r6 * thenExpr + notr7 * elseExpr);
}
}
void megaInit(void) 
{ 


  {

}
}
unsigned long _1_main_flag_func_2(int left , int right , unsigned long thenExpr ,
                                  unsigned long elseExpr ) 
{ 
  register unsigned long tmp5 ;
  unsigned long r6 ;
  unsigned long notr7 ;

  {
  __asm__  volatile   ("cmpl %[right], %[left]\n;\t"
                       "pushf\n;\t"
                       "popq %[tmp5]\n;\t": [tmp5] "=r" (tmp5): [left] "r" (left),
                       [right] "r" (right));
  r6 = ((tmp5 >> 6) & 1) & 1;
  notr7 = ~ r6 & 1;
  return (r6 * thenExpr + notr7 * elseExpr);
}
}
int main(int _formal_argc , char **_formal_argv , char **_formal_envp ) 
{ 
  int base ;
  char input[21] ;
  int _BARRIER_0 ;
  unsigned long _1_main_next ;
  unsigned long _1_main_then8 ;
  unsigned long _1_main_else9 ;
  int r10 ;
  int notr11 ;
  void *addr12 ;
  unsigned long _1_main_then13 ;
  unsigned long _1_main_else14 ;
  int r15 ;
  int notr16 ;
  void *addr17 ;
  unsigned long _1_main_then18 ;
  unsigned long _1_main_else19 ;
  int r20 ;
  int notr21 ;
  void *addr22 ;
  unsigned long _1_main_then23 ;
  unsigned long _1_main_else24 ;
  int r25 ;
  int notr26 ;
  void *addr27 ;
  unsigned long _1_main_then28 ;
  unsigned long _1_main_else29 ;
  int r30 ;
  int notr31 ;
  void *addr32 ;
  unsigned long _1_main_then33 ;
  unsigned long _1_main_else34 ;
  unsigned long __cil_tmp35 ;
  unsigned long _1_main_then36 ;
  unsigned long _1_main_else37 ;
  int r38 ;
  int notr39 ;
  void *addr40 ;
  unsigned long _1_main_then41 ;
  unsigned long _1_main_else42 ;
  unsigned long __cil_tmp43 ;
  unsigned long _1_main_then44 ;
  unsigned long _1_main_else45 ;
  unsigned long __cil_tmp46 ;
  unsigned long _1_main_then47 ;
  unsigned long _1_main_else48 ;
  int r49 ;
  int notr50 ;
  void *addr51 ;
  unsigned long _1_main_then52 ;
  unsigned long _1_main_else53 ;
  int r54 ;
  int notr55 ;
  void *addr56 ;
  unsigned long _1_main_then57 ;
  unsigned long _1_main_else58 ;
  unsigned long __cil_tmp59 ;

  {
  megaInit();
  _global_argc = _formal_argc;
  _global_argv = _formal_argv;
  _global_envp = _formal_envp;
  _BARRIER_0 = 1;
  {
  _1_main_next = 3UL;
  }
  while (1) {
    switch (_1_main_next) {
    case 41: ;
    r10 = ((int )input[1] == base + 8) != 0;
    notr11 = ! r10;
    _1_main_then8 = 37UL;
    _1_main_else9 = 13UL;
    addr12 = (void *)(r10 * _1_main_then8 + notr11 * _1_main_else9);
    {
    _1_main_next = addr12;
    }
    break;
    case 11: ;
    r15 = ((int )input[12] == base - 5) != 0;
    notr16 = ! r15;
    _1_main_then13 = 17UL;
    _1_main_else14 = 36UL;
    addr17 = (void *)(r15 * _1_main_then13 + notr16 * _1_main_else14);
    {
    _1_main_next = addr17;
    }
    break;
    case 13: 
    puts("Incorrect!!");
    {
    _1_main_next = 15UL;
    }
    break;
    case 2: ;
    r20 = ((int )input[19] == base + 25) != 0;
    notr21 = ! r20;
    _1_main_then18 = 0UL;
    _1_main_else19 = 9UL;
    addr22 = (void *)(r20 * _1_main_then18 + notr21 * _1_main_else19);
    {
    _1_main_next = addr22;
    }
    break;
    case 20: 
    puts("Incorrect!!");
    {
    _1_main_next = 15UL;
    }
    break;
    case 31: ;
    if ((int )input[17] == base + 21) {
      {
      _1_main_next = 23UL;
      }
    } else {
      {
      _1_main_next = 25UL;
      }
    }
    break;
    case 37: ;
    r25 = ((int )input[2] == base - 3) != 0;
    notr26 = ! r25;
    _1_main_then23 = 12UL;
    _1_main_else24 = 22UL;
    addr27 = (void *)(r25 * _1_main_then23 + notr26 * _1_main_else24);
    {
    _1_main_next = addr27;
    }
    break;
    case 0: 
    puts("Correct!!");
    {
    _1_main_next = 15UL;
    }
    break;
    case 21: 
    puts("Incorrect!!");
    {
    _1_main_next = 15UL;
    }
    break;
    case 38: 
    puts("Incorrect!!");
    {
    _1_main_next = 15UL;
    }
    break;
    case 9: 
    puts("Incorrect!!");
    {
    _1_main_next = 15UL;
    }
    break;
    case 22: 
    puts("Incorrect!!");
    {
    _1_main_next = 15UL;
    }
    break;
    case 5: ;
    r30 = ((int )input[16] == base + 14) != 0;
    notr31 = ! r30;
    _1_main_then28 = 31UL;
    _1_main_else29 = 35UL;
    addr32 = (void *)(r30 * _1_main_then28 + notr31 * _1_main_else29);
    {
    _1_main_next = addr32;
    }
    break;
    case 18: 
    puts("Incorrect!!");
    {
    _1_main_next = 15UL;
    }
    break;
    case 19: 
    puts("Incorrect!!");
    {
    _1_main_next = 15UL;
    }
    break;
    case 39: ;
    _1_main_then33 = 28UL;
    _1_main_else34 = 26UL;
    __cil_tmp35 = _1_main_flag_func_0((int )input[14], base + 10, _1_main_then33,
                                      _1_main_else34);
    {
    _1_main_next = __cil_tmp35;
    }
    break;
    case 36: 
    puts("Incorrect!!");
    {
    _1_main_next = 15UL;
    }
    break;
    case 27: ;
    r38 = ((int )input[6] == base + 14) != 0;
    notr39 = ! r38;
    _1_main_then36 = 30UL;
    _1_main_else37 = 40UL;
    addr40 = (void *)(r38 * _1_main_then36 + notr39 * _1_main_else37);
    {
    _1_main_next = addr40;
    }
    break;
    case 7: ;
    if ((int )input[4] == base + 23) {
      {
      _1_main_next = 8UL;
      }
    } else {
      {
      _1_main_next = 38UL;
      }
    }
    break;
    case 24: 
    puts("Incorrect!!");
    {
    _1_main_next = 15UL;
    }
    break;
    case 16: ;
    _1_main_then41 = 41UL;
    _1_main_else42 = 24UL;
    __cil_tmp43 = _1_main_flag_func_1((int )input[0], base + 2, _1_main_then41, _1_main_else42);
    {
    _1_main_next = __cil_tmp43;
    }
    break;
    case 10: ;
    if ((int )input[10] == base - 52) {
      {
      _1_main_next = 29UL;
      }
    } else {
      {
      _1_main_next = 21UL;
      }
    }
    break;
    case 34: 
    puts("Incorrect!!");
    {
    _1_main_next = 15UL;
    }
    break;
    case 3: 
    base = 100;
    fgets((char */* __restrict  */)(input), 21, (FILE */* __restrict  */)stdin);
    {
    _1_main_next = 16UL;
    }
    break;
    case 33: 
    puts("Incorrect!!");
    {
    _1_main_next = 15UL;
    }
    break;
    case 26: 
    puts("Incorrect!!");
    {
    _1_main_next = 15UL;
    }
    break;
    case 1: ;
    if ((int )input[8] == base - 5) {
      {
      _1_main_next = 6UL;
      }
    } else {
      {
      _1_main_next = 18UL;
      }
    }
    break;
    case 25: 
    puts("Incorrect!!");
    {
    _1_main_next = 15UL;
    }
    break;
    case 40: 
    puts("Incorrect!!");
    {
    _1_main_next = 15UL;
    }
    break;
    case 29: ;
    _1_main_then44 = 11UL;
    _1_main_else45 = 20UL;
    __cil_tmp46 = _1_main_flag_func_2((int )input[11], base + 17, _1_main_then44,
                                      _1_main_else45);
    {
    _1_main_next = __cil_tmp46;
    }
    break;
    case 8: ;
    r49 = ((int )input[5] == base - 48) != 0;
    notr50 = ! r49;
    _1_main_then47 = 27UL;
    _1_main_else48 = 4UL;
    addr51 = (void *)(r49 * _1_main_then47 + notr50 * _1_main_else48);
    {
    _1_main_next = addr51;
    }
    break;
    case 32: 
    puts("Incorrect!!");
    {
    _1_main_next = 15UL;
    }
    break;
    case 28: ;
    if ((int )input[15] == base + 3) {
      {
      _1_main_next = 5UL;
      }
    } else {
      {
      _1_main_next = 34UL;
      }
    }
    break;
    case 35: 
    puts("Incorrect!!");
    {
    _1_main_next = 15UL;
    }
    break;
    case 23: ;
    if ((int )input[18] == base - 37) {
      {
      _1_main_next = 2UL;
      }
    } else {
      {
      _1_main_next = 42UL;
      }
    }
    break;
    case 14: 
    puts("Incorrect!!");
    {
    _1_main_next = 15UL;
    }
    break;
    case 6: ;
    r54 = ((int )input[9] == base + 21) != 0;
    notr55 = ! r54;
    _1_main_then52 = 10UL;
    _1_main_else53 = 32UL;
    addr56 = (void *)(r54 * _1_main_then52 + notr55 * _1_main_else53);
    {
    _1_main_next = addr56;
    }
    break;
    case 15: ;
    return (0);
    break;
    case 4: 
    puts("Incorrect!!");
    {
    _1_main_next = 15UL;
    }
    break;
    case 30: ;
    if ((int )input[7] == base - 49) {
      {
      _1_main_next = 1UL;
      }
    } else {
      {
      _1_main_next = 14UL;
      }
    }
    break;
    case 42: 
    puts("Incorrect!!");
    {
    _1_main_next = 15UL;
    }
    break;
    case 17: ;
    if ((int )input[13] == base - 3) {
      {
      _1_main_next = 39UL;
      }
    } else {
      {
      _1_main_next = 33UL;
      }
    }
    break;
    case 12: ;
    _1_main_then57 = 7UL;
    _1_main_else58 = 19UL;
    __cil_tmp59 = _1_main_flag_func_3((int )input[3], base + 3, _1_main_then57, _1_main_else58);
    {
    _1_main_next = __cil_tmp59;
    }
    break;
    }
  }
}
}
